apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgByoA5I4I4VCsWymGr5DAXPxbNY0Y5D6RgHebq2dAgFQgLXA0zPNB4a/do259A4i5FihIG/QEJDrqbgkeBtFWO+RMDT2VB2d28stp3Zmx9TWssB7UXGKG/XSACWCtGn3wT/Nn9jg4IHyf0rsPRWkMStUq10uozWDdVJuKM5hSQ1CYbA3GPnnyNi142uDLyJ5fcYOBkmIk9okNU+Mm1EtJh/cGjZc3UCqmtpUfLrzoleTQxmdpbqzkLcsjr2xW4ZtVB6lINQmrAVK2r9XIhkUvQEgTuCv/q3xcKZbIWEtzR040/tXF2lOL/paz3ZHh+/znTds7aLPJxlKOBR1gpjQT0jbhYG6l9SnDuml2up28dxvYA6UMDN4sYPJO+8tAiOH7PuR9WosQYTz3fFvrFdgdeZcYv5nnJ89BHap4ZJ7PSnABW2CmDzgo8BLomEQesxjyhnyfB9peyx8i+k4H+23lAW3yUAW9fhojc4j0qE+T/rI7Sroj8sGWuw949Qgh8xRh8nVBOVP6wEDcYlRIvh5qG9lrfcNL2J+agBClVf4et7jIxADP1MLpm870WY3J7sDYwlSsduU/bW4E0drRI2q4YMpRNWrO6gv5y5I4n08pfw9NkrEDzX++fvchc+q3mhEJRXpLUzLMRNRJqbch0OAe5cmUu8tOu3lp5rV17GwWldKDfZAv24UK1tAHRdFWy7AJ9FLUNb/A0JWw==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-prod
    type: Opaque

