apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-manager-binding
  namespace: b2bi-prod
subjects:
  - kind: ServiceAccount
    name: default
    namespace: b2bi-prod
roleRef:
  kind: Role
  name: secret-manager
  apiGroup: rbac.authorization.k8s.io
